name: test

on:
  workflow_dispatch:
  pull_request:
    branches: master
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]
    paths-ignore:
      - 'README.md'
  push:
    branches: master
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        ConnectionStrings__Spark: ${{ secrets.ConnectionStrings__Spark }}
        AccessTokenCredentials__Tenant: ${{ secrets.AccessTokenCredentials__Tenant }}
        AccessTokenCredentials__ClientId: ${{ secrets.AccessTokenCredentials__ClientId }}
        AccessTokenCredentials__ClientSecret: ${{ secrets.AccessTokenCredentials__ClientSecret }}
      run: dotnet test --no-build --verbosity normal
